version: '3.8'

services:
  users:
    build:
      context: ./users_service
    container_name: users_service
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      DB_HOST: 192.168.100.49
      DB_USER: root
      DB_PASS: admin
      DB_NAME: ecommerce_users
      DB_PORT: 3306
      JWT_SECRET: shhhhhhhhhhhhh

  products:
    build:
      context: ./products_service
    container_name: products_service
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      DB_HOST: 192.168.100.49
      DB_USER: carlostr
      DB_PASSWORD: carlostr
      DB_NAME: ecommerce_products
      DB_PORT: 5432
      AUTH_ADDRESS: users_service:3000
      KAFKA_HOST: kafka-1
      KAFKA_PORT: 9092

  orders:
    build:
      context: ./orders_service
    container_name: orders_service
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      DB_HOST: 192.168.100.49
      DB_USER: root
      DB_PASS: admin
      DB_NAME: ecommerce_orders
      DB_PORT: 3306
      KAFKA_HOST: kafka-1
      KAFKA_PORT: 9092

  kafka-1: 
    image: bitnami/kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=3c628b23-922c-4c21-888f-de3520060ea5
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:
