apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: carlostranquilinocr98/ecommerce:products
          imagePullPolicy: Always
          env:
            - name: DB_USER
              value: "carlostr"
            - name: DB_PASSWORD
              value: "carlostr"
            - name: DB_HOST
              value: "192.168.100.49"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "ecommerce_products"
            - name: AUTH_ADDRESS
              value: "users-service:3000"
