apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: carlostranquilinocr98/ecommerce:users
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "192.168.100.49"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "admin"
            - name: DB_NAME
              value: "ecommerce_users"
            - name: DB_PORT
              value: "3306"
            - name: JWT_SECRET
              value: "shhhhhhhhhhhhh"
