spring:
  application:
    name: orders

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: never

  kafka:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
      consumer:
        group-id: orders-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 4000
  address: 0.0.0.0

logging:
  level:
    org.hibernate.SQL: info
