spring:
  application:
    name: orders

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: never

server:
  port: 4000
  address: 0.0.0.0

logging:
  level:
    org.hibernate.SQL: info
