"""Remove programmed_deletion column from products

Revision ID: 1781fe8c98f8
Revises: ba686050360d
Create Date: 2025-10-25 17:54:38.641751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1781fe8c98f8'
down_revision: Union[str, Sequence[str], None] = 'ba686050360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_products_name_trgm'), table_name='products', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('products', 'programmed_deletion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('programmed_deletion', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_products_name_trgm'), 'products', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
